config/routes.rb
Rails.application.routes.draw do
  resources :habits
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[ show edit update destroy ]

  # GET /habits or /habits.json
  def index
    @habits = Habit.all
  end

  # GET /habits/1 or /habits/1.json
  def show
  end

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    @habit = Habit.new(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habit_url(@habit), notice: "Habit was successfully created." }
        format.json { render :show, status: :created, location: @habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to habit_url(@habit), notice: "Habit was successfully updated." }
        format.json { render :show, status: :ok, location: @habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy

    respond_to do |format|
      format.html { redirect_to habits_url, notice: "Habit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.require(:habit).permit(:user_id, :name, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/habits/_form.html.erb
<%= form_with(model: habit) do |form| %>
  <% if habit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(habit.errors.count, "error") %> prohibited this habit from being saved:</h2>

      <ul>
        <% habit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_area :note %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/habits/_habit.html.erb
<div id="<%= dom_id habit %>">
  <p>
    <strong>User:</strong>
    <%= habit.user_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= habit.name %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= habit.note %>
  </p>

</div>

app/views/habits/edit.html.erb
<h1>Editing habit</h1>

<%= render "form", habit: @habit %>

<br>

<div>
  <%= link_to "Show this habit", @habit %> |
  <%= link_to "Back to habits", habits_path %>
</div>

app/views/habits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Habits</h1>

<div id="habits">
  <% @habits.each do |habit| %>
    <%= render habit %>
    <p>
      <%= link_to "Show this habit", habit %>
    </p>
  <% end %>
</div>

<%= link_to "New habit", new_habit_path %>

app/views/habits/new.html.erb
<h1>New habit</h1>

<%= render "form", habit: @habit %>

<br>

<div>
  <%= link_to "Back to habits", habits_path %>
</div>

app/views/habits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @habit %>

<div>
  <%= link_to "Edit this habit", edit_habit_path(@habit) %> |
  <%= link_to "Back to habits", habits_path %>

  <%= button_to "Destroy this habit", @habit, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>